const Data = [
  {
    Address1: 'JL Rudal No 38',
    Address2: 'Kel. : Joglo Kec.: Kembangan',
    Bill2CustId: '',
    Bill2CustNo: '',
    Blocked: 0,
    BlockedNote: '',
    City: 'Jakarta Barat',
    CreditLimit: 0,
    CustCode: '00001',
    CustName: 'Budi Arianto',
    DeliveryAddr: '',
    FaxNo: '',
    IsIndividu: 1,
    PayTermCode: '',
    PhoneNo: '0864525235',
    PostCode: '123456',
    SalesCode: '',
    alamat: 'JL Rudal No 38',
    alamatktp: 'Jl Rudal V',
    alamatperusahaan: 'Jl fatmawati',
    alamatreferensi: 'Jl Benda',
    almtperusahnpasangan: '',
    asing: 0,
    bussinesgroup: '',
    collector: '',
    collector_id: '71259840-CFDE-11EA-8B31-4BB039267B1E',
    collector_name: 'Sigit Setiaji',
    compcode: '01',
    createby: 'ekok',
    customer_group: '',
    customer_id: '',
    email: 'budiarianto.wp@gmail.com',
    emailpasangan: '',
    gaji: 0,
    hubunganreferensi: 'Adik Kandung',
    isdeleted: 0,
    jmltanggungan: 0,
    jnskelamin: 'l',
    kdposperusahnpasangan: '',
    kecamatan: 'Kembangan',
    kecamatanktp: 'Kembangan',
    kecamatanperusahaan: '',
    kecamatanreferensi: 'Jagakarsa',
    kecperusahnpasangan: '',
    kelperusahnpasangan: '',
    kelurahan: 'Joglo',
    kelurahanktp: 'Joglo',
    kelurahanperusahaan: '',
    kelurahanreferensi: 'Ciganjur',
    kepemilikanusaha: '0',
    kepmlknusahapasangan: '',
    kewarganegaraan: 'WNI',
    kodepos: '',
    kodeposktp: '123456',
    kodeposperusahaan: '',
    kodeposreferensi: '',
    kota: 'Jakarta Barat',
    kotaktp: 'Jakarata Barat',
    kotaperusahaan: 'Jakarta Selatan',
    kotaperusahnpasangan: '',
    kotareferensi: 'Jakarta Selatan',
    lamabekerja: 'A',
    lamabekerjapasangan: null,
    lamakerjasblm_bln: 0,
    lamakerjasblm_thn: 0,
    lamatinggalbln: 0,
    lamatinggalthn: 12,
    latitude: '',
    longitude: '',
    modified: '2020-08-12T04:50:45.000Z',
    namaibu: 'Sariyem',
    namapasangan: '',
    namaperusahaan: 'Ekoksystem',
    namareferensi: 'Adi Aris ',
    nasabahkey: '01CC8A81-CDB8-11EA-8646-BF0671580B22',
    nmperusahnpasangan: '',
    nofaxperusahaan: '',
    nohandphone: '0864525235',
    nohandphonepasangan: '',
    nohpreferensi: '0324134214',
    noidentitaspasangan: '',
    nomoridentitas: '012312542345',
    notlpperusahaan: '03412341234',
    notlpreferensi: '',
    notlprumah: '0',
    npwp: '',
    npwp_address1: '',
    npwp_address2: '',
    npwp_city: '',
    npwp_name: '',
    npwp_state: '',
    pekerjaanpasangan: '',
    pekerjaansblm_tmpt: '',
    pendidikanpasangan: '',
    pendidikanterakhir: '0',
    pendidikanterakhirinput: '',
    penghasilanpasangan: 0,
    penghasilantambahan: 0,
    provinsi: 'DKI Jakarta',
    provinsiktp: 'DKI Jakarta',
    provinsiperusahaan: 'DKI Jakarta',
    provinsireferensi: 'DKI Jakarta',
    provperusahnpasangan: '',
    sisapendapatan: 0,
    statuspekerjaan: '0',
    statusperkawinan: '0',
    statusrmhtinggal: '0',
    taxbusgrp: 'WAPU',
    tgllahir: '1987-12-31T08:00:00.000Z',
    tgllahirpasangan: null,
    tipepekerjaan: '0',
    tmptlahir: 'Jakarta',
    tmptlahirpasangan: '',
    totalpengeluaran: 0,
    totalpenghasilan: 0,
  },
  {
    Address1:
      'BLOK TELUK JAMBE UTARA                  , RW. 0, KEL. -, KEC. -, KODE POS-',
    Address2: 'Kel. :  Kec.: ',
    Bill2CustId: null,
    Bill2CustNo: null,
    Blocked: 0,
    BlockedNote: null,
    City: '',
    CreditLimit: 0,
    CustCode: '11140000360739',
    CustName: 'DADANG EKA ANTARIKSA                    ',
    DeliveryAddr: null,
    FaxNo: null,
    IsIndividu: null,
    PayTermCode: null,
    PhoneNo: null,
    PostCode: '',
    SalesCode: null,
    alamat:
      'BLOK TELUK JAMBE UTARA                  , RW. 0, KEL. -, KEC. -, KODE POS-',
    alamatktp:
      'BLOK TELUK JAMBE UTARA                  , RW. 0, KEL. -, KEC. -, KODE POS-',
    alamatperusahaan: null,
    alamatreferensi: null,
    almtperusahnpasangan: null,
    asing: 0,
    bussinesgroup: null,
    collector: null,
    collector_id: null,
    collector_name: null,
    compcode: '01',
    createby: 'ekok',
    customer_group: 'AGENCY',
    customer_id: '',
    email: null,
    emailpasangan: null,
    gaji: 0,
    hubunganreferensi: null,
    isdeleted: 0,
    jmltanggungan: null,
    jnskelamin: 'l',
    kdposperusahnpasangan: null,
    kecamatan: '',
    kecamatanktp: '',
    kecamatanperusahaan: null,
    kecamatanreferensi: null,
    kecperusahnpasangan: null,
    kelperusahnpasangan: null,
    kelurahan: '',
    kelurahanktp: '',
    kelurahanperusahaan: null,
    kelurahanreferensi: null,
    kepemilikanusaha: null,
    kepmlknusahapasangan: null,
    kewarganegaraan: null,
    kodepos: '',
    kodeposktp: '',
    kodeposperusahaan: null,
    kodeposreferensi: null,
    kota: '',
    kotaktp: '',
    kotaperusahaan: null,
    kotaperusahnpasangan: null,
    kotareferensi: null,
    lamabekerja: null,
    lamabekerjapasangan: null,
    lamakerjasblm_bln: 0,
    lamakerjasblm_thn: 0,
    lamatinggalbln: 0,
    lamatinggalthn: 0,
    latitude: null,
    longitude: null,
    modified: '2020-08-13T05:14:31.000Z',
    namaibu: null,
    namapasangan: null,
    namaperusahaan: null,
    namareferensi: null,
    nasabahkey: '89F51A00-D211-11EA-A8AB-F56E41C14706',
    nmperusahnpasangan: null,
    nofaxperusahaan: null,
    nohandphone: null,
    nohandphonepasangan: null,
    nohpreferensi: null,
    noidentitaspasangan: null,
    nomoridentitas: null,
    notlpperusahaan: null,
    notlpreferensi: null,
    notlprumah: null,
    npwp: null,
    npwp_address1: null,
    npwp_address2: null,
    npwp_city: '',
    npwp_name: null,
    npwp_state: '',
    pekerjaanpasangan: null,
    pekerjaansblm_tmpt: null,
    pendidikanpasangan: null,
    pendidikanterakhir: null,
    pendidikanterakhirinput: null,
    penghasilanpasangan: 0,
    penghasilantambahan: 0,
    provinsi: null,
    provinsiktp: null,
    provinsiperusahaan: null,
    provinsireferensi: null,
    provperusahnpasangan: null,
    sisapendapatan: 0,
    statuspekerjaan: null,
    statusperkawinan: null,
    statusrmhtinggal: null,
    taxbusgrp: 'WAPU',
    tgllahir: null,
    tgllahirpasangan: null,
    tipepekerjaan: null,
    tmptlahir: null,
    tmptlahirpasangan: null,
    totalpengeluaran: 0,
    totalpenghasilan: 0,
  },
  {
    Address1:
      'BANJAR MANDAR                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
    Address2: 'Kel. :  Kec.: ',
    Bill2CustId: null,
    Bill2CustNo: null,
    Blocked: 0,
    BlockedNote: null,
    City: '',
    CreditLimit: 0,
    CustCode: '11290000061163',
    CustName: 'SALIM                                   ',
    DeliveryAddr: null,
    FaxNo: null,
    IsIndividu: null,
    PayTermCode: null,
    PhoneNo: null,
    PostCode: '',
    SalesCode: null,
    alamat:
      'BANJAR MANDAR                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
    alamatktp:
      'BANJAR MANDAR                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
    alamatperusahaan: null,
    alamatreferensi: null,
    almtperusahnpasangan: null,
    asing: 0,
    bussinesgroup: null,
    collector: null,
    collector_id: null,
    collector_name: null,
    compcode: '01',
    createby: 'ekok',
    customer_group: 'AGENCY',
    customer_id: '',
    email: null,
    emailpasangan: null,
    gaji: 0,
    hubunganreferensi: null,
    isdeleted: 0,
    jmltanggungan: null,
    jnskelamin: 'l',
    kdposperusahnpasangan: null,
    kecamatan: '',
    kecamatanktp: '',
    kecamatanperusahaan: null,
    kecamatanreferensi: null,
    kecperusahnpasangan: null,
    kelperusahnpasangan: null,
    kelurahan: '',
    kelurahanktp: '',
    kelurahanperusahaan: null,
    kelurahanreferensi: null,
    kepemilikanusaha: null,
    kepmlknusahapasangan: null,
    kewarganegaraan: null,
    kodepos: '',
    kodeposktp: '',
    kodeposperusahaan: null,
    kodeposreferensi: null,
    kota: '',
    kotaktp: '',
    kotaperusahaan: null,
    kotaperusahnpasangan: null,
    kotareferensi: null,
    lamabekerja: null,
    lamabekerjapasangan: null,
    lamakerjasblm_bln: 0,
    lamakerjasblm_thn: 0,
    lamatinggalbln: 0,
    lamatinggalthn: 0,
    latitude: null,
    longitude: null,
    modified: '2020-08-13T05:14:31.000Z',
    namaibu: null,
    namapasangan: null,
    namaperusahaan: null,
    namareferensi: null,
    nasabahkey: '89F51A01-D211-11EA-A8AB-F56E41C14706',
    nmperusahnpasangan: null,
    nofaxperusahaan: null,
    nohandphone: null,
    nohandphonepasangan: null,
    nohpreferensi: null,
    noidentitaspasangan: null,
    nomoridentitas: null,
    notlpperusahaan: null,
    notlpreferensi: null,
    notlprumah: null,
    npwp: null,
    npwp_address1: null,
    npwp_address2: null,
    npwp_city: '',
    npwp_name: null,
    npwp_state: '',
    pekerjaanpasangan: null,
    pekerjaansblm_tmpt: null,
    pendidikanpasangan: null,
    pendidikanterakhir: null,
    pendidikanterakhirinput: null,
    penghasilanpasangan: 0,
    penghasilantambahan: 0,
    provinsi: null,
    provinsiktp: null,
    provinsiperusahaan: null,
    provinsireferensi: null,
    provperusahnpasangan: null,
    sisapendapatan: 0,
    statuspekerjaan: null,
    statusperkawinan: null,
    statusrmhtinggal: null,
    taxbusgrp: 'WAPU',
    tgllahir: null,
    tgllahirpasangan: null,
    tipepekerjaan: null,
    tmptlahir: null,
    tmptlahirpasangan: null,
    totalpengeluaran: 0,
    totalpenghasilan: 0,
  },
  // {
  //   Address1:
  //     'PERUM DALUNG PERMAI BLOK VV NO 1        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11290000394464',
  //   CustName: 'SUYONO AHMAD FAUZAN                     ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'PERUM DALUNG PERMAI BLOK VV NO 1        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'PERUM DALUNG PERMAI BLOK VV NO 1        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: '89F51A02-D211-11EA-A8AB-F56E41C14706',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'MENTAWAK ULU                            , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11230000539334',
  //   CustName: 'MUSTAKIM                                ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'MENTAWAK ULU                            , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'MENTAWAK ULU                            , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: '89F51A03-D211-11EA-A8AB-F56E41C14706',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'DUSUN MERANTI                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11290000051503',
  //   CustName: 'SARDIYANTO                              ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'DUSUN MERANTI                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'DUSUN MERANTI                           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD791B20-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'TANAH ABANG                             , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11290000074004',
  //   CustName: 'SUPARNO                                 ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'TANAH ABANG                             , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'TANAH ABANG                             , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD791B21-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'DUSUN MOJO                              , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11300000217594',
  //   CustName: 'TRIMO                                   ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'DUSUN MOJO                              , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'DUSUN MOJO                              , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD791B22-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'KUNCEN RT 006 RW 002 DESA KUNCEN KEC    , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11150000353131',
  //   CustName: 'ERNAWATI                                ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'KUNCEN RT 006 RW 002 DESA KUNCEN KEC    , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'KUNCEN RT 006 RW 002 DESA KUNCEN KEC    , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD791B23-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'JL.BHAKTI KARANG NO.20                  , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11160000203764',
  //   CustName: 'FREDRICH MAURITS HENDRIMARIO BEBOK      ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'JL.BHAKTI KARANG NO.20                  , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'JL.BHAKTI KARANG NO.20                  , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD794230-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'JALAN MBAH SOMA RT.001 RW.001           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11180000329971',
  //   CustName: 'HARJO WINOTO                            ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'JALAN MBAH SOMA RT.001 RW.001           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'JALAN MBAH SOMA RT.001 RW.001           , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD794231-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'DUSUN GUNA WAKTU                        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11110000060131',
  //   CustName: 'AMIN                                    ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'DUSUN GUNA WAKTU                        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'DUSUN GUNA WAKTU                        , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD794232-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
  // {
  //   Address1:
  //     'KOMP UNAND B III/13 NO 15               , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   Address2: 'Kel. :  Kec.: ',
  //   Bill2CustId: null,
  //   Bill2CustNo: null,
  //   Blocked: 0,
  //   BlockedNote: null,
  //   City: '',
  //   CreditLimit: 0,
  //   CustCode: '11290000040251',
  //   CustName: 'SUSMIATI                                ',
  //   DeliveryAddr: null,
  //   FaxNo: null,
  //   IsIndividu: null,
  //   PayTermCode: null,
  //   PhoneNo: null,
  //   PostCode: '',
  //   SalesCode: null,
  //   alamat:
  //     'KOMP UNAND B III/13 NO 15               , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatktp:
  //     'KOMP UNAND B III/13 NO 15               , RT. 0, RW. 0, KEL. -, KEC. -, KODE POS-',
  //   alamatperusahaan: null,
  //   alamatreferensi: null,
  //   almtperusahnpasangan: null,
  //   asing: 0,
  //   bussinesgroup: null,
  //   collector: null,
  //   collector_id: null,
  //   collector_name: null,
  //   compcode: '01',
  //   createby: 'ekok',
  //   customer_group: 'AGENCY',
  //   customer_id: '',
  //   email: null,
  //   emailpasangan: null,
  //   gaji: 0,
  //   hubunganreferensi: null,
  //   isdeleted: 0,
  //   jmltanggungan: null,
  //   jnskelamin: 'l',
  //   kdposperusahnpasangan: null,
  //   kecamatan: '',
  //   kecamatanktp: '',
  //   kecamatanperusahaan: null,
  //   kecamatanreferensi: null,
  //   kecperusahnpasangan: null,
  //   kelperusahnpasangan: null,
  //   kelurahan: '',
  //   kelurahanktp: '',
  //   kelurahanperusahaan: null,
  //   kelurahanreferensi: null,
  //   kepemilikanusaha: null,
  //   kepmlknusahapasangan: null,
  //   kewarganegaraan: null,
  //   kodepos: '',
  //   kodeposktp: '',
  //   kodeposperusahaan: null,
  //   kodeposreferensi: null,
  //   kota: '',
  //   kotaktp: '',
  //   kotaperusahaan: null,
  //   kotaperusahnpasangan: null,
  //   kotareferensi: null,
  //   lamabekerja: null,
  //   lamabekerjapasangan: null,
  //   lamakerjasblm_bln: 0,
  //   lamakerjasblm_thn: 0,
  //   lamatinggalbln: 0,
  //   lamatinggalthn: 0,
  //   latitude: null,
  //   longitude: null,
  //   modified: '2020-08-13T05:14:31.000Z',
  //   namaibu: null,
  //   namapasangan: null,
  //   namaperusahaan: null,
  //   namareferensi: null,
  //   nasabahkey: 'FD794233-D176-11EA-92BC-1BD7909B3FA5',
  //   nmperusahnpasangan: null,
  //   nofaxperusahaan: null,
  //   nohandphone: null,
  //   nohandphonepasangan: null,
  //   nohpreferensi: null,
  //   noidentitaspasangan: null,
  //   nomoridentitas: null,
  //   notlpperusahaan: null,
  //   notlpreferensi: null,
  //   notlprumah: null,
  //   npwp: null,
  //   npwp_address1: null,
  //   npwp_address2: null,
  //   npwp_city: '',
  //   npwp_name: null,
  //   npwp_state: '',
  //   pekerjaanpasangan: null,
  //   pekerjaansblm_tmpt: null,
  //   pendidikanpasangan: null,
  //   pendidikanterakhir: null,
  //   pendidikanterakhirinput: null,
  //   penghasilanpasangan: 0,
  //   penghasilantambahan: 0,
  //   provinsi: null,
  //   provinsiktp: null,
  //   provinsiperusahaan: null,
  //   provinsireferensi: null,
  //   provperusahnpasangan: null,
  //   sisapendapatan: 0,
  //   statuspekerjaan: null,
  //   statusperkawinan: null,
  //   statusrmhtinggal: null,
  //   taxbusgrp: 'WAPU',
  //   tgllahir: null,
  //   tgllahirpasangan: null,
  //   tipepekerjaan: null,
  //   tmptlahir: null,
  //   tmptlahirpasangan: null,
  //   totalpengeluaran: 0,
  //   totalpenghasilan: 0,
  // },
];

export default Data;
